--- # EC2 SNAPSHOT MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks: 
  - name: Take a snapshot of the running instance root volume
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-09a0355fe9c4c02eb
      device_name: /dev/sda1
      description: Root Volume Snapshot Taken During Ansible Course
      wait: no
    register: snapshot
