- name: StartHttpd
  service: name={{ apache_pkg }} state=started
- name: TestHttpd
  get_url: 
    url: http://{{ apache_fqdn }}
    dest: /home/ansible/abc.txt
  register: result
- name: DisplayResult
  debug: var=result
